#---------------------------------------------------
#General Parameters 
#---------------------------------------------------
ALL: "photoreceptors"
SAMPLES: "samples.tsv"
ANNOFILE: "annotations.txt"
SUBSET: "Cones"

